# Generated by Django 4.2 on 2023-05-19 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='cuser',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='seller',
            new_name='cuser',
        ),
    ]
